name: Terraform-GitHub-Actions
on: workflow_dispatch
env:
 AWS_ACCESS_KEY_ID: AKIAR4HMVUUY364IJVWL
 AWS_SECRET_ACCESS_KEY: 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
 AWS_DEFAULT_REGION: us-west-2
 ECR_REPOSITORY: demo-project
 PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
 PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
 IMAGE_TAG: sample_image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         run: ssh -i "AP.pem" ec2-user@ec2-35-89-75-182.us-west-2.compute.amazonaws.com
         
   
