name: Terraform-GitHub-Actions
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: AKIAR4HMVUUY364IJVWL
  AWS_SECRET_ACCESS_KEY: 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
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login ec2
        env:
          PRIVATE_KEY: SHA256:mXX6+xN28UO2W1pnuAT7tL2bjdwnLhef0qMUt1QSU7k sreekanth a@APSS-LAP-41
          HOSTNAME: ec2-35-89-75-182.us-west-2.compute.amazonaws.com
          USER_NAME: ec2-user
