name: Terraform-GitHub-Actions
on: workflow_dispatch
env:
 AWS_ACCESS_KEY_ID: AKIAR4HMVUUY364IJVWL
 AWS_SECRET_ACCESS_KEY: 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
 AWS_DEFAULT_REGION: us-west-2
 ECR_REPOSITORY: demo-project
 PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
 PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
 IMAGE_TAG: sample_image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2 
       - name: Deploy in EC2
         env:
            PRIVATE_KEY:  ${{ secrets.AWS_SSH_KEY_PRIVATE }}
            HOSTNAME : ec2-35-89-75-182.us-west-2.compute.amazonaws.com
            USER_NAME : ec2-user
            
         run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
         
   
