name: Terraform-GitHub-Actions
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: AKIAR4HMVUUY364IJVWL
  AWS_SECRET_ACCESS_KEY: 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
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: SHA256:mXX6+xN28UO2W1pnuAT7tL2bjdwnLhef0qMUt1QSU7k sreekanth a@APSS-LAP-41
          REMOTE_HOST: "ec2-35-89-75-182.us-west-2.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
      - name: creating a file
        run: touch sai
