name: Terraform-GitHub-Actions
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: AKIAR4HMVUUY364IJVWL
  AWS_SECRET_ACCESS_KEY: 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
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configuring AWS credentials

      
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ssh -i "AP.pem" ec2-user@ec2-35-89-75-182.us-west-2.compute.amazonaws.com
          SOURCE: "./"
          run: chmod 400 AP.pem
          REMOTE_HOST: "ec2-35-89-75-182.us-west-2.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
      - name: craeting file
        run: touch sai
        
