name: Terraform-GitHub-Actions
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: AKIAR4HMVUUY364IJVWL
  AWS_SECRET_ACCESS_KEY: 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
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - name: Configuring AWS credentials
      - uses: actions/checkout@v2
      - name: Login ec2
        env:
          PRIVATE_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ec2-35-89-75-182.us-west-2.compute.amazonaws.com
          USER_NAME: ec2-user
      - name: fiile
        run: touch sai
        
